name: Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Call update webhook
        run: curl http://herbarifontiquer.cat:9000/hooks/herbari-csv

        
